# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98a408711eb563224675ab40bd0e599a08c78663a71d17216b93ccdb9225c71deee193239239513f96cc416b24c516c12bfdb2dda540d45f6f8f08d99dded75e

test:
  secret_key_base: 2c29c3582b254cbcf15d36692f9141a55ed8cee6e4a9abffe96fd51bf76b8413ea25eb1b8fe3829c054159fc8bf082e9aba8ebcdd7c83cab5e600e46e585c850

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
